"""Generated PHP function signatures from JetBrains phpstorm-stubs.

Do not edit by hand. Regenerate with tools/gen_php_completions.py.
"""

PHP_GENERATED = {
    'PS_UNRESERVE_PREFIX___halt_compiler': '()',
    'PS_UNRESERVE_PREFIX_array': '(...$_)',
    'PS_UNRESERVE_PREFIX_die': '($status = "")',
    'PS_UNRESERVE_PREFIX_empty': '($var)',
    'PS_UNRESERVE_PREFIX_eval': '($code)',
    'PS_UNRESERVE_PREFIX_exit': '($status = "")',
    'PS_UNRESERVE_PREFIX_isset': '($var, ...$_)',
    'PS_UNRESERVE_PREFIX_list': '($var1, ...$_)',
    'PS_UNRESERVE_PREFIX_unset': '($var, ...$_)',
    'abs': '(int|float $num): int|float',
    'acos': '(float $num): float',
    'acosh': '(float $num): float',
    'addcslashes': '(string $string, string $characters): string',
    'addslashes': '(string $string): string',
    'apache_request_headers': '(): false|array',
    'array_all': '(array $array, callable $callback): bool',
    'array_any': '(array $array, callable $callback): bool',
    'array_change_key_case': '(array $array, int $case = CASE_LOWER): array',
    'array_chunk': '(array $array, int $length, bool $preserve_keys = false): array',
    'array_column': '(array $array, string|int|null $column_key, string|int|null $index_key = null): array',
    'array_combine': '(array $keys, array $values): array|false',
    'array_count_values': '(array $array): array',
    'array_diff': '(array $array, $arrays, array ...$arrays): array',
    'array_diff_assoc': '(array $array, $arrays, array ...$arrays): array',
    'array_diff_key': '(array $array, $arrays, array ...$arrays): array',
    'array_diff_uassoc': '(array $array, array $array2, callable $key_compare_func, ...$rest,): array',
    'array_diff_ukey': '(array $array, array $array2, callable $key_compare_func, ...$rest,): array',
    'array_fill': '(int $start_index, int $count, mixed $value): array',
    'array_fill_keys': '(array $keys, mixed $value): array',
    'array_filter': '(array $array, ?callable $callback = null, int $mode = 0): array',
    'array_find': '(array $array, callable $callback): mixed',
    'array_find_key': '(array $array, callable $callback): mixed',
    'array_first': '(array $array): mixed',
    'array_flip': '(array $array): array',
    'array_intersect': '(array $array, $arrays, array ...$arrays): array',
    'array_intersect_assoc': '(array $array, $arrays, array ...$arrays): array',
    'array_intersect_key': '(array $array, $arrays, array ...$arrays): array',
    'array_intersect_uassoc': '(array $array, array $array2, callable $key_compare_func, ...$rest): array',
    'array_intersect_ukey': '(array $array, array $array2, callable $key_compare_func, ...$rest): array',
    'array_is_list': '(array $array): bool',
    'array_key_exists': '($key, $array): bool',
    'array_key_first': '(array $array): string|int|null',
    'array_key_last': '(array $array): string|int|null',
    'array_keys': '(array $array, mixed $filter_value, bool $strict = false): array',
    'array_last': '(array $array): mixed',
    'array_map': '(?callable $callback, array $array, $arrays, array ...$arrays): array',
    'array_merge': '($array, $arrays, array ...$arrays): array',
    'array_merge_recursive': '(array $arr1, array $arrays, array ...$arrays): array',
    'array_multisort': '(&$array, $sort_order = SORT_ASC, $sort_flags = SORT_REGULAR, &...$rest)',
    'array_pad': '(array $array, int $length, mixed $value): array',
    'array_pop': '(array &$array): mixed',
    'array_product': '(array $array): int|float',
    'array_push': '(array &$array, $values, mixed ...$values): int',
    'array_rand': '(array $array, int $num = 1): array|string|int',
    'array_reduce': '(array $array, callable $callback, mixed $initial = null): mixed',
    'array_replace': '(array $array, $replacements, array ...$replacements): array',
    'array_replace_recursive': '(array $array, $replacements, array ...$replacements): array',
    'array_reverse': '(array $array, bool $preserve_keys = false): array',
    'array_search': '(mixed $needle, array $haystack, bool $strict = false): string|int|false',
    'array_shift': '(array &$array): mixed',
    'array_slice': '(array $array, int $offset, ?int $length = null, bool $preserve_keys = false): array',
    'array_splice': '(array &$array, int $offset, ?int $length = null, mixed $replacement = []): array',
    'array_sum': '(array $array): int|float',
    'array_udiff': '(array $array, array $array2, callable $data_compare_func, ...$rest,): array',
    'array_udiff_assoc': '(array $array, array $array2, callable $data_compare_func, ...$rest,): array',
    'array_udiff_uassoc': '(array $array, array $array2, callable $data_compare_func, callable $key_compare_func, ...$rest): array',
    'array_uintersect': '(array $array, array $array2, callable $data_compare_func, ...$rest): array',
    'array_uintersect_assoc': '(array $array, array $array2, callable $data_compare_func, ...$rest): array',
    'array_uintersect_uassoc': '(array $array, array $array2, callable $data_compare_func, callable $key_compare_func, ...$rest): array',
    'array_unique': '(array $array, int $flags = SORT_STRING): array',
    'array_unshift': '(array &$array, $values, mixed ...$values): int',
    'array_values': '(array $array): array',
    'array_walk': '(object|array &$array, callable $callback, mixed $arg)',
    'array_walk_recursive': '(object|array &$array, callable $callback, mixed $arg)',
    'arsort': '(array &$array, int $flags = SORT_REGULAR)',
    'asin': '(float $num): float',
    'asinh': '(float $num): float',
    'asort': '(array &$array, int $flags = SORT_REGULAR)',
    'assert': '(mixed $assertion, $description = null): bool',
    'assert_options': '(int $option, mixed $value): mixed',
    'atan': '(float $num): float',
    'atan2': '(float $y, float $x): float',
    'atanh': '(float $num): float',
    'base64_decode': '(string $string, bool $strict = false): string|false',
    'base64_encode': '(string $string): string',
    'base_convert': '(string $num, int $from_base, int $to_base): string',
    'basename': '(string $path, string $suffix = \'\'): string',
    'bin2hex': '(string $string): string',
    'bindec': '(string $binary_string): int|float',
    'boolval': '(mixed $value): bool',
    'call_user_func': '(callable $callback, mixed ...$args): mixed',
    'call_user_func_array': '(callable $callback, array $args): mixed',
    'call_user_method': '(string $method_name, object &$obj, ...$parameter): mixed',
    'call_user_method_array': '(string $method_name, object &$obj, array $params): mixed',
    'ceil': '(int|float $num)',
    'chdir': '(string $directory): bool',
    'checkdate': '(int $month, int $day, int $year): bool',
    'checkdnsrr': '(string $hostname, string $type = \'MX\'): bool',
    'chgrp': '(string $filename, string|int $group): bool',
    'chmod': '(string $filename, int $permissions): bool',
    'chop': '(string $string, string $characters = " \\n\\r\\t\\v\\0"): string',
    'chown': '(string $filename, string|int $user): bool',
    'chr': '(int $codepoint): string',
    'chroot': '(string $directory): bool',
    'chunk_split': '(string $string, int $length = 76, string $separator = "\\r\\n"): string',
    'class_alias': '(string $class, string $alias, bool $autoload = true): bool',
    'class_exists': '(string $class, bool $autoload = true): bool',
    'clearstatcache': '(bool $clear_realpath_cache = false, string $filename = \'\'): void',
    'cli_get_process_title': '(): ?string',
    'cli_set_process_title': '(string $title): bool',
    'clone': '(object $object, array $withProperties = []): object',
    'closedir': '($dir_handle = null): void',
    'closelog': '()',
    'compact': '($var_name, $var_names = null, ...$var_names): array',
    'confirm_pdo_ibm_compiled': '()',
    'connection_aborted': '(): int',
    'connection_status': '(): int',
    'constant': '(string $name): mixed',
    'convert_cyr_string': '(string $str, string $from, string $to): string',
    'convert_uudecode': '(string $string): string|false',
    'convert_uuencode': '(string $string): string',
    'copy': '(string $from, string $to, $context = null): bool',
    'cos': '(float $num): float',
    'cosh': '(float $num): float',
    'count': '(Countable|array $value, int $mode = COUNT_NORMAL): int',
    'count_chars': '(string $string, int $mode = 0): array|string',
    'crc32': '(string $string): int',
    'create_function': '(string $args, string $code): false|string',
    'crypt': '($string, $salt): ?string',
    'curl_close': '($handle): void',
    'curl_copy_handle': '($handle)',
    'curl_errno': '($handle): int',
    'curl_error': '($handle): string',
    'curl_escape': '($handle, string $string): string|false',
    'curl_exec': '($handle): string|bool',
    'curl_file_create': '(string $filename, ?string $mime_type = null, ?string $posted_filename = null): CURLFile',
    'curl_getinfo': '($handle, ?int $option = null): mixed',
    'curl_init': '(?string $url = null)',
    'curl_multi_add_handle': '($multi_handle, $handle): int',
    'curl_multi_close': '($multi_handle): void',
    'curl_multi_errno': '($multi_handle): int',
    'curl_multi_exec': '($multi_handle, &$still_running = 0, &$still_running): int',
    'curl_multi_get_handles': '(CurlMultiHandle $multi_handle): array',
    'curl_multi_getcontent': '($handle): ?string',
    'curl_multi_info_read': '($multi_handle, &$queued_messages = null): array|false',
    'curl_multi_init': '(): CurlMultiHandle',
    'curl_multi_remove_handle': '($multi_handle, $handle)',
    'curl_multi_select': '($multi_handle, float $timeout = 1.0): int',
    'curl_multi_setopt': '($multi_handle, int $option, mixed $value): bool',
    'curl_multi_strerror': '(int $error_code): ?string',
    'curl_pause': '($handle, int $flags): int',
    'curl_reset': '($handle): void',
    'curl_setopt': '($handle, int $option, mixed $value): bool',
    'curl_setopt_array': '($handle, array $options): bool',
    'curl_share_close': '($share_handle): void',
    'curl_share_errno': '($share_handle): int',
    'curl_share_init': '()',
    'curl_share_init_persistent': '(array $share_options): CurlSharePersistentHandle',
    'curl_share_setopt': '($share_handle, int $option, mixed $value): bool',
    'curl_share_strerror': '(int $error_code): ?string',
    'curl_strerror': '(int $error_code): ?string',
    'curl_unescape': '($handle, string $string): string|false',
    'curl_upkeep': '(CurlHandle $handle): bool',
    'curl_version': '($age = null): array|false',
    'current': '(object|array $array): mixed',
    'date': '(string $format, ?int $timestamp = null)',
    'date_add': '(DateTime $object, DateInterval $interval)',
    'date_create': '(string $datetime = \'now\', ?DateTimeZone $timezone = null): DateTime|false',
    'date_create_from_format': '(string $format, string $datetime, ?DateTimeZone $timezone = null): DateTime|false',
    'date_create_immutable': '(string $datetime = \'now\', ?DateTimeZone $timezone = null): DateTimeImmutable|false',
    'date_create_immutable_from_format': '(string $format, string $datetime, ?DateTimeZone $timezone = null): DateTimeImmutable|false',
    'date_date_set': '(DateTime $object, int $year, int $month, int $day): DateTime|false',
    'date_default_timezone_get': '(): string',
    'date_default_timezone_set': '(string $timezoneId): bool',
    'date_diff': '(DateTimeInterface $baseObject, DateTimeInterface $targetObject, bool $absolute = false)',
    'date_format': '(DateTimeInterface $object, string $format)',
    'date_get_last_errors': '(): array|false',
    'date_interval_create_from_date_string': '(string $datetime): DateInterval|false',
    'date_interval_format': '(DateInterval $object, string $format): string',
    'date_isodate_set': '(DateTime $object, int $year, int $week, int $dayOfWeek = 1)',
    'date_modify': '(DateTime $object, string $modifier): DateTime|false',
    'date_offset_get': '(DateTimeInterface $object)',
    'date_parse': '(string $datetime): false|array',
    'date_parse_from_format': '(string $format, string $datetime): array',
    'date_sub': '(DateTime $object, DateInterval $interval)',
    'date_sun_info': '(int $timestamp, float $latitude, float $longitude): array|false',
    'date_sunrise': '(int $timestamp, int $returnFormat = SUNFUNCS_RET_STRING, ?float $latitude = null, ?float $longitude = null, ?float $zenith = null, ?float $utcOffset = null): string|int|float|false',
    'date_sunset': '(int $timestamp, int $returnFormat = SUNFUNCS_RET_STRING, ?float $latitude = null, ?float $longitude = null, ?float $zenith = null, ?float $utcOffset = null): string|int|float|false',
    'date_time_set': '(DateTime $object, int $hour, int $minute, int $second = 0, int $microsecond = 0): DateTime',
    'date_timestamp_get': '(DateTimeInterface $object): int',
    'date_timestamp_set': '(DateTime $object, int $timestamp): DateTime|false',
    'date_timezone_get': '(DateTimeInterface $object): DateTimeZone|false',
    'date_timezone_set': '($object, DateTimeZone $timezone)',
    'debug_backtrace': '(int $options = DEBUG_BACKTRACE_PROVIDE_OBJECT, int $limit = 0): array',
    'debug_print_backtrace': '(int $options = 0, int $limit = 0): void',
    'debug_zval_dump': '(mixed $value, $values = null, mixed ...$values): void',
    'decbin': '(int $num): string',
    'dechex': '(int $num): string',
    'decoct': '(int $num): string',
    'define': '(string $constant_name, $value, bool $case_insensitive = false): bool',
    'define_syslog_variables': '()',
    'defined': '(string $constant_name): bool',
    'deg2rad': '(float $num): float',
    'die': '(string|int $status = 0): never',
    'dir': '(string $directory, $context = null): Directory|false',
    'dirname': '(string $path, int $levels = 1): string',
    'disk_free_space': '(string $directory): float|false',
    'disk_total_space': '(string $directory): float|false',
    'diskfreespace': '(string $directory): float|false',
    'dl': '(string $extension_filename): bool',
    'dns_check_record': '(string $hostname, string $type = \'MX\'): bool',
    'dns_get_mx': '(string $hostname, &$hosts, &$weights = null): bool',
    'dns_get_record': '(string $hostname, int $type = DNS_ANY, &$authoritative_name_servers = null, &$additional_records = null, bool $raw = false): array|false',
    'doubleval': '(mixed $value): float',
    'each': '(&$array): array',
    'end': '(object|array &$array): mixed',
    'enum_exists': '(string $enum, bool $autoload = true): bool',
    'error_clear_last': '(): void',
    'error_get_last': '(): ?array',
    'error_log': '(string $message, int $message_type = 0, ?string $destination = null, ?string $additional_headers = null): bool',
    'error_reporting': '(?int $error_level = null): int',
    'escapeshellarg': '(string $arg): string',
    'escapeshellcmd': '(string $command): string',
    'exec': '(string $command, &$output = null, &$result_code = null): string|false',
    'exit': '(string|int $status = 0): never',
    'exp': '(float $num): float',
    'explode': '(string $separator, string $string, int $limit = PHP_INT_MAX)',
    'expm1': '(float $num): float',
    'extension_loaded': '(string $extension): bool',
    'extract': '(array &$array, int $flags = EXTR_OVERWRITE, string $prefix = ""): int',
    'ezmlm_hash': '(string $addr): int',
    'fclose': '($stream): bool',
    'fdatasync': '($stream): bool',
    'fdiv': '(float $num1, float $num2): float',
    'feof': '($stream): bool',
    'fflush': '($stream): bool',
    'fgetc': '($stream): string|false',
    'fgetcsv': '($stream, ?int $length = null, string $separator = \',\', string $enclosure = \'"\', string $escape = \'\\\\\')',
    'fgets': '($stream, ?int $length = null): string|false',
    'fgetss': '($handle, ?int $length = null, $allowable_tags = null): false|string',
    'file': '(string $filename, int $flags = 0, $context = null): array|false',
    'file_exists': '(string $filename): bool',
    'file_get_contents': '(string $filename, bool $use_include_path = false, $context = null, int $offset = 0, ?int $length = null): string|false',
    'file_put_contents': '(string $filename, mixed $data, int $flags = 0, $context = null): int|false',
    'fileatime': '(string $filename): int|false',
    'filectime': '(string $filename): int|false',
    'filegroup': '(string $filename): int|false',
    'fileinode': '(string $filename): int|false',
    'filemtime': '(string $filename): int|false',
    'fileowner': '(string $filename): int|false',
    'fileperms': '(string $filename): int|false',
    'filesize': '(string $filename): int|false',
    'filetype': '(string $filename): string|false',
    'finfo_buffer': '($finfo, string $string, int $flags = FILEINFO_NONE, $context = null): string|false',
    'finfo_close': '($finfo)',
    'finfo_file': '($finfo, string $filename, int $flags = 0, $context = null): string|false',
    'finfo_open': '(int $flags = 0, ?string $magic_database = null)',
    'finfo_set_flags': '($finfo, int $flags)',
    'floatval': '(mixed $value): float',
    'flock': '($stream, int $operation, &$would_block = null): bool',
    'floor': '(int|float $num)',
    'flush': '(): void',
    'fmod': '(float $num1, float $num2): float',
    'fnmatch': '(string $pattern, string $filename, int $flags = 0): bool',
    'fopen': '(string $filename, string $mode, bool $use_include_path = false, $context = null)',
    'forward_static_call': '(callable $callback, mixed ...$args): mixed',
    'forward_static_call_array': '(callable $callback, array $args): mixed',
    'fpassthru': '($stream)',
    'fpow': '(float $num, float $exponent): float',
    'fprintf': '($stream, string $format, mixed ...$values): int',
    'fputcsv': '($stream, array $fields, string $separator = ",", string $enclosure = \'"\', string $escape = "\\\\", string $eol = "\\n"): int|false',
    'fputs': '($stream, string $data, ?int $length = null): int|false',
    'fread': '($stream, int $length): string|false',
    'fscanf': '($stream, string $format, mixed &...$vars): array|int|false|null',
    'fseek': '($stream, int $offset, int $whence = SEEK_SET): int',
    'fsockopen': '(string $hostname, int $port = -1, int $port = -1, &$error_code = null, &$error_message = null, ?float $timeout = null)',
    'fstat': '($stream): array|false',
    'fsync': '($stream): bool',
    'ftell': '($stream): int|false',
    'ftok': '(string $filename, string $project_id): int',
    'ftruncate': '($stream, int $size): bool',
    'func_get_arg': '(int $position): mixed',
    'func_get_args': '(): array',
    'func_num_args': '(): int',
    'function_exists': '(string $function): bool',
    'fwrite': '($stream, string $data, ?int $length = null): int|false',
    'gc_collect_cycles': '(): int',
    'gc_disable': '(): void',
    'gc_enable': '(): void',
    'gc_enabled': '(): bool',
    'gc_mem_caches': '(): int',
    'gc_status': '(): array',
    'get_browser': '(?string $user_agent = null, bool $return_array = false): object|array|false',
    'get_called_class': '(): string',
    'get_cfg_var': '(string $option): array|string|false',
    'get_class': '(object $object): string',
    'get_class_methods': '(object|string $object_or_class): array',
    'get_class_vars': '(string $class): array',
    'get_current_user': '(): string',
    'get_debug_type': '(mixed $value): string',
    'get_declared_classes': '(): array',
    'get_declared_interfaces': '(): array',
    'get_declared_traits': '(): array',
    'get_defined_constants': '(bool $categorize = false): array',
    'get_defined_functions': '(bool $exclude_disabled = true): array',
    'get_defined_vars': '(): array',
    'get_error_handler': '(): ?callable',
    'get_exception_handler': '(): ?callable',
    'get_extension_funcs': '(string $extension): array|false',
    'get_headers': '(string $url, $associative = false, $context = null): array|false',
    'get_html_translation_table': '(int $table = 0, int $flags = ENT_QUOTES|ENT_SUBSTITUTE, string $encoding = "UTF-8"): array',
    'get_include_path': '(): string|false',
    'get_included_files': '(): array',
    'get_loaded_extensions': '(bool $zend_extensions = false): array',
    'get_magic_quotes_gpc': '(): int',
    'get_magic_quotes_runtime': '(): int',
    'get_mangled_object_vars': '(object $object): array',
    'get_meta_tags': '(string $filename, bool $use_include_path = false): array|false',
    'get_object_vars': '(object $object): array',
    'get_parent_class': '(object|string $object_or_class): string|false',
    'get_required_files': '(): array',
    'get_resource_id': '($resource): int',
    'get_resource_type': '($resource): string',
    'get_resources': '(?string $type = null): array',
    'getallheaders': '(): false|array',
    'getcwd': '(): string|false',
    'getdate': '(?int $timestamp = null): array',
    'getdir': '(string $directory, $context = null): Directory|false',
    'getenv': '($varname, ?string $name = null, bool $local_only = false): array|string|false',
    'gethostbyaddr': '(string $ip): string|false',
    'gethostbyname': '(string $hostname): string',
    'gethostbynamel': '(string $hostname): array|false',
    'gethostname': '(): string|false',
    'getimagesize': '(string $filename, &$image_info = null): array|false',
    'getimagesizefromstring': '(string $string, &$image_info = null): array|false',
    'getlastmod': '(): int|false',
    'getmxrr': '(string $hostname, &$hosts, &$weights = null): bool',
    'getmygid': '(): int|false',
    'getmyinode': '(): int|false',
    'getmypid': '(): int|false',
    'getmyuid': '(): int|false',
    'getopt': '(string $short_options, array $long_options = [], &$rest_index = null): array|false',
    'getprotobyname': '(string $protocol): int|false',
    'getprotobynumber': '(int $protocol): string|false',
    'getrusage': '(int $mode = 0): array|false',
    'getservbyname': '(string $service, string $protocol): int|false',
    'getservbyport': '(int $port, string $protocol): string|false',
    'gettimeofday': '(bool $as_float = false): array|float',
    'gettype': '(mixed $value): string',
    'glob': '(string $pattern, int $flags = 0): array|false',
    'gmdate': '(string $format, ?int $timestamp = null)',
    'gmmktime': '(int $hour = null, int $hour, ?int $minute = null, ?int $second = null, ?int $month = null, ?int $day = null, ?int $year = null, $is_dst = null): int|false',
    'gmstrftime': '(string $format, ?int $timestamp = null): string|false',
    'header': '(string $header, bool $replace = true, int $response_code = 0): void',
    'header_register_callback': '(callable $callback): bool',
    'header_remove': '(?string $name = null): void',
    'headers_list': '(): array',
    'headers_sent': '(&$filename = null, &$line = null): bool',
    'hebrev': '(string $string, int $max_chars_per_line = 0): string',
    'hebrevc': '(string $hebrew_text, $max_chars_per_line = 0): string',
    'hex2bin': '(string $string): string|false',
    'hexdec': '(string $hex_string): int|float',
    'highlight_file': '(string $filename, bool $return = false): string|bool',
    'highlight_string': '(string $string, bool $return = false)',
    'hrtime': '(bool $as_number = false): array|int|float|false',
    'html_entity_decode': '(string $string, int $flags = ENT_QUOTES|ENT_SUBSTITUTE, ?string $encoding = null): string',
    'htmlentities': '(string $string, int $flags = ENT_QUOTES|ENT_SUBSTITUTE, ?string $encoding = null, bool $double_encode = true): string',
    'htmlspecialchars': '(string $string, int $flags = ENT_QUOTES|ENT_SUBSTITUTE, ?string $encoding = null, bool $double_encode = true): string',
    'htmlspecialchars_decode': '(string $string, int $flags = ENT_QUOTES|ENT_SUBSTITUTE): string',
    'http_build_query': '(object|array $data, string $numeric_prefix = "", ?string $arg_separator = null, int $encoding_type = PHP_QUERY_RFC1738): string',
    'http_clear_last_response_headers': '(): void',
    'http_get_last_response_headers': '(): ?array',
    'http_response_code': '(int $response_code = 0): int|bool',
    'hypot': '(float $x, float $y): float',
    'idate': '(string $format, ?int $timestamp = null): int|false',
    'ignore_user_abort': '(?bool $enable = null): int',
    'image_type_to_extension': '(int $image_type, bool $include_dot = true): string|false',
    'image_type_to_mime_type': '(int $image_type): string',
    'implode': '(array|string $separator = "", ?array $array = null): string',
    'import_request_variables': '(string $types, $prefix = null): bool',
    'in_array': '(mixed $needle, array $haystack, bool $strict = false): bool',
    'inet_ntop': '(string $ip): string|false',
    'inet_pton': '(string $ip): string|false',
    'ini_alter': '(string $option, $value): string|false',
    'ini_get': '(string $option): string|false',
    'ini_get_all': '(?string $extension = null, bool $details = true): array|false',
    'ini_parse_quantity': '(string $shorthand): int',
    'ini_restore': '(string $option): void',
    'ini_set': '(string $option, $value): string|false',
    'intdiv': '(int $num1, int $num2): int',
    'interface_exists': '(string $interface, bool $autoload = true): bool',
    'intval': '(mixed $value, int $base = 10): int',
    'ip2long': '(string $ip): int|false',
    'iptcembed': '(string $iptc_data, string $filename, int $spool = 0): string|bool',
    'iptcparse': '(string $iptc_block): array|false',
    'is_a': '(mixed $object_or_class, string $class, bool $allow_string = false): bool',
    'is_array': '(mixed $value): bool',
    'is_bool': '(mixed $value): bool',
    'is_callable': '(mixed $value, bool $syntax_only = false, &$callable_name = null): bool',
    'is_countable': '(mixed $value): bool',
    'is_dir': '(string $filename): bool',
    'is_double': '(mixed $value): bool',
    'is_executable': '(string $filename): bool',
    'is_file': '(string $filename): bool',
    'is_finite': '(float $num): bool',
    'is_float': '(mixed $value): bool',
    'is_infinite': '(float $num): bool',
    'is_int': '(mixed $value): bool',
    'is_integer': '(mixed $value): bool',
    'is_iterable': '(mixed $value): bool',
    'is_link': '(string $filename): bool',
    'is_long': '(mixed $value): bool',
    'is_nan': '(float $num): bool',
    'is_null': '(mixed $value): bool',
    'is_numeric': '(mixed $value): bool',
    'is_object': '(mixed $value): bool',
    'is_readable': '(string $filename): bool',
    'is_real': '(mixed $var): bool',
    'is_resource': '(mixed $value): bool',
    'is_scalar': '(mixed $value): bool',
    'is_string': '(mixed $value): bool',
    'is_subclass_of': '(mixed $object_or_class, string $class, bool $allow_string = true): bool',
    'is_uploaded_file': '(string $filename): bool',
    'is_writable': '(string $filename): bool',
    'is_writeable': '(string $filename): bool',
    'join': '(array|string $separator = "", ?array $array = null): string',
    'json_decode': '(string $json, ?bool $associative = null, int $depth = 512, int $flags = 0): mixed',
    'json_encode': '(mixed $value, int $flags = 0, int $depth = 512): string|false',
    'json_last_error': '(): int',
    'json_last_error_msg': '(): string',
    'json_validate': '(string $json, int $depth = 512, int $flags = 0): bool',
    'key': '(object|array $array): string|int|null',
    'key_exists': '($key, array $array): bool',
    'krsort': '(array &$array, int $flags = SORT_REGULAR)',
    'ksort': '(array &$array, int $flags = SORT_REGULAR)',
    'lcfirst': '(string $string): string',
    'lchgrp': '(string $filename, string|int $group): bool',
    'lchown': '(string $filename, string|int $user): bool',
    'levenshtein': '(string $string1, string $string2, int $insertion_cost = 1, int $replacement_cost = 1, int $deletion_cost = 1): int',
    'link': '(string $target, string $link): bool',
    'linkinfo': '(string $path): int|false',
    'localeconv': '(): array',
    'localtime': '(?int $timestamp = null, bool $associative = false): array',
    'log': '(float $num, float $base = M_E): float',
    'log10': '(float $num): float',
    'log1p': '(float $num): float',
    'long2ip': '(int $ip)',
    'lstat': '(string $filename): array|false',
    'ltrim': '(string $string, string $characters = " \\n\\r\\t\\v\\0"): string',
    'magic_quotes_runtime': '(bool $new_setting)',
    'mail': '(string $to, string $subject, string $message, array|string $additional_headers = [], string $additional_params = \'\'): bool',
    'max': '(mixed $value, mixed $values = null, mixed ...$values): mixed',
    'mb_check_encoding': '(array|string|null $value = null, ?string $encoding = null): bool',
    'mb_chr': '(int $codepoint, ?string $encoding = null): string|false',
    'mb_convert_case': '(string $string, int $mode, ?string $encoding = null): string',
    'mb_convert_encoding': '(array|string $string, string $to_encoding, array|string|null $from_encoding = null): array|string|false',
    'mb_convert_kana': '(string $string, string $mode = \'KV\', ?string $encoding = null): string',
    'mb_convert_variables': '(string $to_encoding, array|string $from_encoding, &$vars = null, mixed &$var, mixed &...$vars): string|false',
    'mb_decode_mimeheader': '(string $string): string',
    'mb_decode_numericentity': '(string $string, array $map, ?string $encoding = null, $is_hex = false)',
    'mb_detect_encoding': '(string $string, array|string|null $encodings = null, bool $strict = false): string|false',
    'mb_detect_order': '(array|string|null $encoding = null): array|bool',
    'mb_encode_mimeheader': '(string $string, ?string $charset = null, ?string $transfer_encoding = null, string $newline = "\\r\\n", int $indent = 0): string',
    'mb_encode_numericentity': '(string $string, array $map, ?string $encoding = null, bool $hex = false): string',
    'mb_encoding_aliases': '(string $encoding)',
    'mb_ereg': '(string $pattern, string $string, &$matches = null): bool',
    'mb_ereg_match': '(string $pattern, string $string, ?string $options = null): bool',
    'mb_ereg_replace': '(string $pattern, string $replacement, string $string, ?string $options = null): string|false|null',
    'mb_ereg_replace_callback': '(string $pattern, callable $callback, string $string, ?string $options = null): string|false|null',
    'mb_ereg_search': '(?string $pattern = null, ?string $options = null): bool',
    'mb_ereg_search_getpos': '(): int',
    'mb_ereg_search_getregs': '(): array|false',
    'mb_ereg_search_init': '(string $string, ?string $pattern = null, ?string $options = null): bool',
    'mb_ereg_search_pos': '(?string $pattern = null, ?string $options = null): array|false',
    'mb_ereg_search_regs': '(?string $pattern = null, ?string $options = null): array|false',
    'mb_ereg_search_setpos': '(int $offset): bool',
    'mb_eregi': '(string $pattern, string $string, &$matches = null): bool',
    'mb_eregi_replace': '(string $pattern, string $replacement, string $string, ?string $options = null): string|false|null',
    'mb_get_info': '(string $type = \'all\')',
    'mb_http_input': '(?string $type = null): array|string|false',
    'mb_http_output': '(?string $encoding = null): string|bool',
    'mb_internal_encoding': '(?string $encoding = null): string|bool',
    'mb_language': '(?string $language = null): string|bool',
    'mb_lcfirst': '(string $string, ?string $encoding = null): string',
    'mb_list_encodings': '(): array',
    'mb_ltrim': '(string $string, ?string $characters = null, ?string $encoding = null): string',
    'mb_ord': '(string $string, ?string $encoding = null): int|false',
    'mb_output_handler': '(string $string, int $status): string',
    'mb_parse_str': '(string $string, &$result): bool',
    'mb_preferred_mime_name': '(string $encoding): string|false',
    'mb_regex_encoding': '(?string $encoding = null): string|bool',
    'mb_regex_set_options': '(?string $options = null): string',
    'mb_rtrim': '(string $string, ?string $characters = null, ?string $encoding = null): string',
    'mb_scrub': '(string $string, ?string $encoding = null): false|string',
    'mb_send_mail': '(string $to, string $subject, string $message, array|string $additional_headers = [], ?string $additional_params = null): bool',
    'mb_split': '(string $pattern, string $string, int $limit = -1): array|false',
    'mb_str_pad': '(string $string, int $length, string $pad_string = " ", int $pad_type = STR_PAD_RIGHT, ?string $encoding = null): string',
    'mb_str_split': '(string $string, int $length = 1, ?string $encoding = null)',
    'mb_strcut': '(string $string, int $start, ?int $length = null, ?string $encoding = null): string',
    'mb_strimwidth': '(string $string, int $start, int $width, string $trim_marker = \'\', ?string $encoding = null): string',
    'mb_stripos': '(string $haystack, string $needle, int $offset = 0, ?string $encoding = null): int|false',
    'mb_stristr': '(string $haystack, string $needle, bool $before_needle = false, ?string $encoding = null): string|false',
    'mb_strlen': '(string $string, $encoding = null)',
    'mb_strpos': '(string $haystack, string $needle, int $offset = 0, ?string $encoding = null): int|false',
    'mb_strrchr': '(string $haystack, string $needle, bool $before_needle = false, ?string $encoding = null): string|false',
    'mb_strrichr': '(string $haystack, string $needle, bool $before_needle = false, ?string $encoding = null): string|false',
    'mb_strripos': '(string $haystack, string $needle, int $offset = 0, ?string $encoding = null): int|false',
    'mb_strrpos': '(string $haystack, string $needle, int $offset = 0, ?string $encoding = null): int|false',
    'mb_strstr': '(string $haystack, string $needle, bool $before_needle = false, ?string $encoding = null): string|false',
    'mb_strtolower': '(string $string, ?string $encoding = null): string',
    'mb_strtoupper': '(string $string, ?string $encoding = null): string',
    'mb_strwidth': '(string $string, ?string $encoding = null): int',
    'mb_substitute_character': '(string|int|null $substitute_character = null): string|int|bool',
    'mb_substr': '(string $string, int $start, ?int $length = null, ?string $encoding = null): string',
    'mb_substr_count': '(string $haystack, string $needle, ?string $encoding = null): int',
    'mb_trim': '(string $string, ?string $characters = null, ?string $encoding = null): string',
    'mb_ucfirst': '(string $string, ?string $encoding = null): string',
    'mbereg': '(string $pattern, string $string, array &$registers)',
    'mbereg_match': '($pattern, $string, $option)',
    'mbereg_replace': '($pattern, $replacement, $string, $option)',
    'mbereg_search': '($pattern, $option)',
    'mbereg_search_getpos': '()',
    'mbereg_search_getregs': '()',
    'mbereg_search_init': '($string, $pattern, $option)',
    'mbereg_search_pos': '($pattern, $option)',
    'mbereg_search_regs': '($pattern, $option)',
    'mbereg_search_setpos': '($position)',
    'mberegi': '(string $pattern, string $string, array &$registers)',
    'mberegi_replace': '($pattern, $replacement, $string, string $option = "msri"): string',
    'mbregex_encoding': '($encoding)',
    'mbsplit': '($pattern, $string, $limit)',
    'md5': '(string $string, bool $binary = false): string',
    'md5_file': '(string $filename, bool $binary = false): string|false',
    'memory_get_peak_usage': '(bool $real_usage = false): int',
    'memory_get_usage': '(bool $real_usage = false): int',
    'memory_reset_peak_usage': '(): void',
    'metaphone': '(string $string, int $max_phonemes = 0)',
    'method_exists': '($object_or_class, string $method): bool',
    'microtime': '(bool $as_float = false): string|float',
    'mime_content_type': '($filename): string|false',
    'min': '(mixed $value, mixed $values = null, mixed ...$values): mixed',
    'mkdir': '(string $directory, int $permissions = 0777, bool $recursive = false, $context = null): bool',
    'mktime': '(int $hour = null, int $hour, ?int $minute = null, ?int $second = null, ?int $month = null, ?int $day = null, ?int $year = null, int $is_dst = -1): int|false',
    'money_format': '(string $format, float $number): ?string',
    'move_uploaded_file': '(string $from, string $to): bool',
    'mysqli_affected_rows': '(mysqli $mysql): string|int',
    'mysqli_autocommit': '(mysqli $mysql, bool $enable): bool',
    'mysqli_begin_transaction': '(mysqli $mysql, int $flags = 0, ?string $name = null): bool',
    'mysqli_bind_param': '(mysqli_stmt $statement, string $types)',
    'mysqli_bind_result': '(mysqli_stmt $statement, string $types, mixed &$var1)',
    'mysqli_change_user': '(mysqli $mysql, string $username, string $password, ?string $database): bool',
    'mysqli_character_set_name': '(mysqli $mysql): string',
    'mysqli_client_encoding': '(mysqli $mysql): string',
    'mysqli_close': '(mysqli $mysql): bool',
    'mysqli_commit': '(mysqli $mysql, int $flags = 0, ?string $name = null): bool',
    'mysqli_connect': '(?string $hostname = null, ?string $username = null, ?string $password = null, ?string $database = null, ?int $port = null, ?string $socket = null): mysqli|false',
    'mysqli_connect_errno': '(): int',
    'mysqli_connect_error': '(): ?string',
    'mysqli_data_seek': '(mysqli_result $result, int $offset): bool',
    'mysqli_debug': '(string $options): bool',
    'mysqli_dump_debug_info': '(mysqli $mysql): bool',
    'mysqli_errno': '(mysqli $mysql): int',
    'mysqli_error': '(mysqli $mysql): string',
    'mysqli_error_list': '(mysqli $mysql): array',
    'mysqli_escape_string': '(mysqli $mysql, string $string, $resultmode = null): string',
    'mysqli_execute': '(mysqli_stmt $statement, ?array $params = null): bool',
    'mysqli_execute_query': '(mysqli $mysql, string $query, ?array $params = null): mysqli_result|bool',
    'mysqli_fetch': '(mysqli_stmt $statement): bool',
    'mysqli_fetch_all': '(mysqli_result $result, int $mode = MYSQLI_NUM): array',
    'mysqli_fetch_array': '(mysqli_result $result, int $mode = MYSQLI_BOTH): array|false|null',
    'mysqli_fetch_assoc': '(mysqli_result $result): array|null|false',
    'mysqli_fetch_column': '(mysqli_result $result, int $column = 0): string|int|float|false|null',
    'mysqli_fetch_field': '(mysqli_result $result): object|false',
    'mysqli_fetch_field_direct': '(mysqli_result $result, int $index): object|false',
    'mysqli_fetch_fields': '(mysqli_result $result): array',
    'mysqli_fetch_lengths': '(mysqli_result $result): array|false',
    'mysqli_fetch_object': '(mysqli_result $result, string $class = \'stdClass\', array $constructor_args = []): object|null|false',
    'mysqli_fetch_row': '(mysqli_result $result): array|false|null',
    'mysqli_field_count': '(mysqli $mysql): int',
    'mysqli_field_seek': '(mysqli_result $result, int $index)',
    'mysqli_field_tell': '(mysqli_result $result): int',
    'mysqli_free_result': '(mysqli_result $result): void',
    'mysqli_get_cache_stats': '(mysqli $mysql)',
    'mysqli_get_charset': '(mysqli $mysql): ?object',
    'mysqli_get_client_info': '(mysqli $mysql = null, ?mysqli $mysql = null)',
    'mysqli_get_client_stats': '(): array',
    'mysqli_get_client_version': '($link): int',
    'mysqli_get_connection_stats': '(mysqli $mysql): array',
    'mysqli_get_host_info': '(mysqli $mysql): string',
    'mysqli_get_links_stats': '(): array',
    'mysqli_get_metadata': '(mysqli_stmt $statement): false|mysqli_result',
    'mysqli_get_proto_info': '(mysqli $mysql): int',
    'mysqli_get_server_info': '(mysqli $mysql): string',
    'mysqli_get_server_version': '(mysqli $mysql): int',
    'mysqli_get_warnings': '(mysqli $mysql): mysqli_warning|false',
    'mysqli_info': '(mysqli $mysql): ?string',
    'mysqli_init': '(): mysqli|false',
    'mysqli_insert_id': '(mysqli $mysql): string|int',
    'mysqli_kill': '(mysqli $mysql, int $process_id): bool',
    'mysqli_more_results': '(mysqli $mysql): bool',
    'mysqli_multi_query': '(mysqli $mysql, string $query, string $query = null, string $query): bool',
    'mysqli_next_result': '(mysqli $mysql): bool',
    'mysqli_num_fields': '(mysqli_result $result): int',
    'mysqli_num_rows': '(mysqli_result $result): string|int',
    'mysqli_options': '(mysqli $mysql, int $option, $value): bool',
    'mysqli_param_count': '(mysqli_stmt $statement): int',
    'mysqli_ping': '(mysqli $mysql): bool',
    'mysqli_poll': '(?array &$read, ?array &$error, array &$reject, int $seconds, int $microseconds = 0): int|false',
    'mysqli_prepare': '(mysqli $mysql, string $query): mysqli_stmt|false',
    'mysqli_query': '(mysqli $mysql, string $query, int $result_mode = MYSQLI_STORE_RESULT): mysqli_result|bool',
    'mysqli_real_connect': '(mysqli $mysql, ?string $hostname = null, ?string $username = null, ?string $password = null, ?string $database = null, ?int $port = null, ?string $socket = null, int $flags = 0): bool',
    'mysqli_real_escape_string': '(mysqli $mysql, string $string): string',
    'mysqli_real_query': '(mysqli $mysql, string $query, string $query = null, string $query): bool',
    'mysqli_reap_async_query': '(mysqli $mysql): mysqli_result|bool',
    'mysqli_refresh': '(mysqli $mysql, int $flags): bool',
    'mysqli_release_savepoint': '(mysqli $mysql, string $name): bool',
    'mysqli_report': '(int $flags)',
    'mysqli_rollback': '(mysqli $mysql, int $flags = 0, ?string $name = null): bool',
    'mysqli_savepoint': '(mysqli $mysql, string $name): bool',
    'mysqli_select_db': '(mysqli $mysql, string $database): bool',
    'mysqli_send_long_data': '(mysqli_stmt $statement, int $param_num, string $data): bool',
    'mysqli_set_charset': '(mysqli $mysql, string $charset): bool',
    'mysqli_set_local_infile_default': '(mysqli $mysql)',
    'mysqli_set_local_infile_handler': '(mysqli $mysql, callable $read_func): bool',
    'mysqli_set_opt': '(mysqli $mysql, int $option, $value): bool',
    'mysqli_sqlstate': '(mysqli $mysql): string',
    'mysqli_ssl_set': '(mysqli $mysql, $key, $certificate, $ca_certificate, $ca_path, $cipher_algos): bool',
    'mysqli_stat': '(mysqli $mysql): string|false',
    'mysqli_stmt_affected_rows': '(mysqli_stmt $statement): string|int',
    'mysqli_stmt_attr_get': '(mysqli_stmt $statement, int $attribute): false|int',
    'mysqli_stmt_attr_set': '(mysqli_stmt $statement, int $attribute, int $value): bool',
    'mysqli_stmt_bind_param': '(mysqli_stmt $statement, string $types, mixed &$vars = null, mixed &...$vars): bool',
    'mysqli_stmt_bind_result': '(mysqli_stmt $statement, mixed &$vars = null, mixed &...$vars): bool',
    'mysqli_stmt_close': '(mysqli_stmt $statement): bool',
    'mysqli_stmt_data_seek': '(mysqli_stmt $statement, int $offset): void',
    'mysqli_stmt_errno': '(mysqli_stmt $statement): int',
    'mysqli_stmt_error': '(mysqli_stmt $statement): string',
    'mysqli_stmt_error_list': '(mysqli_stmt $statement): array',
    'mysqli_stmt_execute': '(mysqli_stmt $statement, ?array $params = null): bool',
    'mysqli_stmt_fetch': '(mysqli_stmt $statement): ?bool',
    'mysqli_stmt_field_count': '(mysqli_stmt $statement): int',
    'mysqli_stmt_free_result': '(mysqli_stmt $statement): void',
    'mysqli_stmt_get_result': '(mysqli_stmt $statement): mysqli_result|false',
    'mysqli_stmt_get_warnings': '(mysqli_stmt $statement): mysqli_warning|false',
    'mysqli_stmt_init': '(mysqli $mysql): mysqli_stmt|false',
    'mysqli_stmt_insert_id': '(mysqli_stmt $statement): string|int',
    'mysqli_stmt_more_results': '(mysqli_stmt $statement): bool',
    'mysqli_stmt_next_result': '(mysqli_stmt $statement): bool',
    'mysqli_stmt_num_rows': '(mysqli_stmt $statement): string|int',
    'mysqli_stmt_param_count': '(mysqli_stmt $statement): int',
    'mysqli_stmt_prepare': '(mysqli_stmt $statement, string $query): bool',
    'mysqli_stmt_reset': '(mysqli_stmt $statement): bool',
    'mysqli_stmt_result_metadata': '(mysqli_stmt $statement): mysqli_result|false',
    'mysqli_stmt_send_long_data': '(mysqli_stmt $statement, int $param_num, string $data): bool',
    'mysqli_stmt_sqlstate': '(mysqli_stmt $statement): string',
    'mysqli_stmt_store_result': '(mysqli_stmt $statement): bool',
    'mysqli_store_result': '(mysqli $mysql, int $mode = 0): mysqli_result|false',
    'mysqli_thread_id': '(mysqli $mysql): int',
    'mysqli_thread_safe': '(): bool',
    'mysqli_use_result': '(mysqli $mysql): mysqli_result|false',
    'mysqli_warning_count': '(mysqli $mysql): int',
    'natcasesort': '(array &$array)',
    'natsort': '(array &$array)',
    'net_get_interfaces': '(): array|false',
    'next': '(object|array &$array): mixed',
    'nl2br': '(string $string, bool $use_xhtml = true): string',
    'nl_langinfo': '(int $item): string|false',
    'number_format': '(float $num, int $decimals = 0, ?string $decimal_separator = \'.\', ?string $thousands_separator = \',\'): string',
    'ob_clean': '(): bool',
    'ob_end_clean': '(): bool',
    'ob_end_flush': '(): bool',
    'ob_flush': '(): bool',
    'ob_get_clean': '(): string|false',
    'ob_get_contents': '(): string|false',
    'ob_get_flush': '(): string|false',
    'ob_get_length': '(): int|false',
    'ob_get_level': '(): int',
    'ob_get_status': '(bool $full_status = false): array',
    'ob_implicit_flush': '($enable = true): void',
    'ob_list_handlers': '(): array',
    'ob_start': '($callback = null, int $chunk_size = 0, int $flags = PHP_OUTPUT_HANDLER_STDFLAGS): bool',
    'octdec': '(string $octal_string): int|float',
    'opendir': '(string $directory, $context = null)',
    'openlog': '(string $prefix, int $flags, int $facility)',
    'ord': '(string $character): int',
    'output_add_rewrite_var': '(string $name, string $value): bool',
    'output_reset_rewrite_vars': '(): bool',
    'pack': '(string $format, $values = null, mixed ...$values)',
    'parse_ini_file': '(string $filename, bool $process_sections = false, int $scanner_mode = INI_SCANNER_NORMAL): array|false',
    'parse_ini_string': '(string $ini_string, bool $process_sections = false, int $scanner_mode = INI_SCANNER_NORMAL): array|false',
    'parse_str': '(string $string, &$result = [], &$result): void',
    'parse_url': '(string $url, int $component = -1): array|string|int|false|null',
    'passthru': '(string $command, &$result_code = null): ?bool',
    'password_algos': '(): array',
    'password_get_info': '(string $hash)',
    'password_hash': '(string $password, string|int|null $algo, array $options = [])',
    'password_needs_rehash': '(string $hash, string|int|null $algo, array $options = []): bool',
    'password_verify': '(string $password, string $hash): bool',
    'pathinfo': '(string $path, int $flags = PATHINFO_ALL): array|string',
    'pclose': '($handle): int',
    'pdo_drivers': '(): array',
    'pfsockopen': '(string $hostname, int $port = -1, int $port = -1, &$error_code = null, &$error_message = null, ?float $timeout = null)',
    'php_egg_logo_guid': '()',
    'php_ini_loaded_file': '(): string|false',
    'php_ini_scanned_files': '(): string|false',
    'php_logo_guid': '(): string',
    'php_real_logo_guid': '()',
    'php_sapi_name': '(): string|false',
    'php_strip_whitespace': '(string $filename): string',
    'php_uname': '(string $mode = \'a\'): string',
    'phpcredits': '(int $flags = CREDITS_ALL): bool',
    'phpinfo': '(int $flags = INFO_ALL): bool',
    'phpversion': '(?string $extension = null): string|false',
    'pi': '(): float',
    'popen': '(string $command, string $mode)',
    'pos': '(object|array $array): mixed',
    'pow': '(mixed $num, mixed $exponent): object|int|float',
    'preg_filter': '(array|string $pattern, array|string $replacement, array|string $subject, int $limit = -1, &$count = null): array|string|null',
    'preg_grep': '(string $pattern, array $array, int $flags = 0): array|false',
    'preg_last_error': '(): int',
    'preg_last_error_msg': '(): string',
    'preg_match': '(string $pattern, string $subject, &$matches = null, int $flags = 0, int $offset = 0): int|false',
    'preg_match_all': '(string $pattern, string $subject, &$matches = null, int $flags = 0, int $offset = 0)',
    'preg_quote': '(string $str, ?string $delimiter = null): string',
    'preg_replace': '(array|string $pattern, array|string $replacement, array|string $subject, int $limit = -1, &$count = null): array|string|null',
    'preg_replace_callback': '(array|string $pattern, callable $callback, array|string $subject, int $limit = -1, &$count = null, int $flags = 0): array|string|null',
    'preg_replace_callback_array': '(array $pattern, array|string $subject, int $limit = -1, &$count = null, int $flags = 0): array|string|null',
    'preg_split': '(string $pattern, string $subject, int $limit = -1, int $flags = 0): array|false',
    'prev': '(object|array &$array): mixed',
    'print_r': '(mixed $value, bool $return = false)',
    'printf': '(string $format, mixed ...$values): int',
    'proc_close': '($process): int',
    'proc_get_status': '($process)',
    'proc_nice': '(int $priority): bool',
    'proc_open': '(array|string $command, array $descriptor_spec, &$pipes, ?string $cwd = null, ?array $env_vars = null, ?array $options = null)',
    'proc_terminate': '($process, int $signal = 15): bool',
    'property_exists': '($object_or_class, string $property): bool',
    'putenv': '(string $assignment): bool',
    'quoted_printable_decode': '(string $string): string',
    'quoted_printable_encode': '(string $string): string',
    'quotemeta': '(string $string): string',
    'rad2deg': '(float $num): float',
    'range': '($start, $end, int|float $step = 1): array',
    'rawurldecode': '(string $string): string',
    'rawurlencode': '(string $string): string',
    'readdir': '($dir_handle = null): string|false',
    'readfile': '(string $filename, bool $use_include_path = false, $context = null): int|false',
    'readlink': '(string $path): string|false',
    'realpath': '(string $path): string|false',
    'realpath_cache_get': '(): array',
    'realpath_cache_size': '(): int',
    'register_shutdown_function': '(callable $callback, mixed ...$args): ?bool',
    'register_tick_function': '(callable $callback, mixed ...$args): bool',
    'rename': '(string $from, string $to, $context = null): bool',
    'request_parse_body': '(?array $options = null): array',
    'reset': '(object|array &$array): mixed',
    'restore_error_handler': '(): bool',
    'restore_exception_handler': '(): bool',
    'restore_include_path': '()',
    'rewind': '($stream): bool',
    'rewinddir': '($dir_handle = null): void',
    'rmdir': '(string $directory, $context = null): bool',
    'round': '(int|float $num, int $precision = 0, $mode = 0, RoundingMode|int $mode = \\RoundingMode::HalfAwayFromZero): float',
    'rsort': '(array &$array, int $flags = SORT_REGULAR)',
    'rtrim': '(string $string, string $characters = " \\n\\r\\t\\v\\0"): string',
    'sapi_windows_cp_conv': '(int|string $in_codepage, int|string $out_codepage, string $subject): ?string',
    'sapi_windows_cp_get': '(string $kind = ""): int',
    'sapi_windows_cp_is_utf8': '(): bool',
    'sapi_windows_cp_set': '(int $codepage): bool',
    'sapi_windows_generate_ctrl_event': '(int $event, int $pid = 0): bool',
    'sapi_windows_set_ctrl_handler': '(?callable $handler, bool $add = true): bool',
    'sapi_windows_vt100_support': '($stream, ?bool $enable = null): bool',
    'scandir': '(string $directory, int $sorting_order = 0, $context = null): array|false',
    'serialize': '(mixed $value): string',
    'set_error_handler': '(?callable $callback, int $error_levels = E_ALL)',
    'set_exception_handler': '(?callable $callback)',
    'set_file_buffer': '($stream, int $size): int',
    'set_include_path': '(string $include_path): string|false',
    'set_magic_quotes_runtime': '(bool $new_setting): bool',
    'set_socket_blocking': '($socket, bool $mode): bool',
    'set_time_limit': '(int $seconds): bool',
    'setcookie': '(string $name, string $value = "", int $expires_or_options = 0, string $path = "", string $domain = "", bool $secure = false, bool $httponly = false): bool',
    'setlocale': '(int $category, $locales, $rest = null, ...$rest): string|false',
    'setrawcookie': '(string $name, $value = \'\', $expires_or_options = 0, $path = "", $domain = "", $secure = false, $httponly = false): bool',
    'settype': '(mixed &$var, string $type): bool',
    'sha1': '(string $string, bool $binary = false): string',
    'sha1_file': '(string $filename, bool $binary = false): string|false',
    'shell_exec': '(string $command): string|false|null',
    'show_source': '(string $filename, bool $return = false): string|bool',
    'shuffle': '(array &$array)',
    'similar_text': '(string $string1, string $string2, &$percent = null): int',
    'sin': '(float $num): float',
    'sinh': '(float $num): float',
    'sizeof': '(Countable|array $value, int $mode = COUNT_NORMAL): int',
    'sleep': '(int $seconds)',
    'socket_get_status': '($stream): array',
    'socket_set_blocking': '($stream, bool $enable): bool',
    'socket_set_timeout': '($stream, int $seconds, int $microseconds = 0, int $microseconds = 0): bool',
    'sort': '(array &$array, int $flags = SORT_REGULAR)',
    'soundex': '(string $string): string',
    'sprintf': '(string $format, $values = null, mixed ...$values): string',
    'sqrt': '(float $num): float',
    'sscanf': '(string $string, string $format, mixed &...$vars): array|int|null',
    'stat': '(string $filename): array|false',
    'str_contains': '(string $haystack, string $needle): bool',
    'str_decrement': '(string $string): string',
    'str_ends_with': '(string $haystack, string $needle): bool',
    'str_getcsv': '(string $string, string $separator = ",", string $enclosure = \'"\', string $escape = "\\\\"): array',
    'str_increment': '(string $string): string',
    'str_ireplace': '(array|string $search, array|string $replace, array|string $subject, &$count = null): array|string',
    'str_pad': '(string $string, int $length, string $pad_string = " ", int $pad_type = STR_PAD_RIGHT): string',
    'str_repeat': '(string $string, int $times): string',
    'str_replace': '(array|string $search, array|string $replace, array|string $subject, &$count = null): array|string',
    'str_rot13': '(string $string): string',
    'str_shuffle': '(string $string): string',
    'str_split': '(string $string, int $length = 1): array|false',
    'str_starts_with': '(string $haystack, string $needle): bool',
    'str_word_count': '(string $string, int $format = 0, ?string $characters = null): array|int',
    'strcasecmp': '(string $string1, string $string2): int',
    'strchr': '(string $haystack, string $needle, bool $before_needle = false): string|false',
    'strcmp': '(string $string1, string $string2): int',
    'strcoll': '(string $string1, string $string2): int',
    'strcspn': '(string $string, string $characters, int $offset = 0, ?int $length = null): int',
    'stream_bucket_append': '($brigade, $bucket): void',
    'stream_bucket_make_writeable': '($brigade)',
    'stream_bucket_new': '($stream, string $buffer)',
    'stream_bucket_prepend': '($brigade, $bucket): void',
    'stream_context_create': '(?array $options = null, ?array $params = null)',
    'stream_context_get_default': '(?array $options = null)',
    'stream_context_get_options': '($stream_or_context): array',
    'stream_context_get_params': '($context): array',
    'stream_context_set_default': '(array $options)',
    'stream_context_set_option': '($context, string $wrapper_or_options, string $option_name, mixed $value)',
    'stream_context_set_options': '($context, array $options)',
    'stream_context_set_params': '($context, array $params)',
    'stream_copy_to_stream': '($from, $to, ?int $length = null, int $offset = 0): int|false',
    'stream_filter_append': '($stream, string $filter_name, int $mode = 0, mixed $params)',
    'stream_filter_prepend': '($stream, string $filter_name, int $mode = 0, mixed $params)',
    'stream_filter_register': '(string $filter_name, string $class): bool',
    'stream_filter_remove': '($stream_filter): bool',
    'stream_get_contents': '($stream, ?int $length = null, int $offset = -1): string|false',
    'stream_get_filters': '(): array',
    'stream_get_line': '($stream, int $length, string $ending = \'\'): string|false',
    'stream_get_meta_data': '($stream): array',
    'stream_get_transports': '(): array',
    'stream_get_wrappers': '(): array',
    'stream_is_local': '($stream): bool',
    'stream_isatty': '($stream): bool',
    'stream_register_wrapper': '(string $protocol, string $class, int $flags = 0): bool',
    'stream_resolve_include_path': '(string $filename): string|false',
    'stream_select': '(?array &$read, ?array &$write, ?array &$except, ?int $seconds, $microseconds = null): int|false',
    'stream_set_blocking': '($stream, bool $enable): bool',
    'stream_set_chunk_size': '($stream, int $size)',
    'stream_set_read_buffer': '($stream, int $size): int',
    'stream_set_timeout': '($stream, int $seconds, int $microseconds = 0, int $microseconds = 0): bool',
    'stream_set_write_buffer': '($stream, int $size): int',
    'stream_socket_accept': '($socket, ?float $timeout = null, &$peer_name = null)',
    'stream_socket_client': '(string $address, &$error_code = null, &$error_message = null, ?float $timeout = null, int $flags = STREAM_CLIENT_CONNECT, $context = null)',
    'stream_socket_enable_crypto': '($stream, bool $enable, ?int $crypto_method = null, $session_stream = null): int|bool',
    'stream_socket_get_name': '($socket, bool $remote): string|false',
    'stream_socket_pair': '(int $domain, int $type, int $protocol): array|false',
    'stream_socket_recvfrom': '($socket, int $length, int $flags = 0, &$address = null): string|false',
    'stream_socket_sendto': '($socket, string $data, int $flags = 0, string $address = \'\'): int|false',
    'stream_socket_server': '(string $address, &$error_code = null, &$error_message = null, int $flags = STREAM_SERVER_BIND|STREAM_SERVER_LISTEN, $context = null)',
    'stream_socket_shutdown': '($stream, int $mode): bool',
    'stream_supports_lock': '($stream): bool',
    'stream_wrapper_register': '(string $protocol, string $class, int $flags = 0): bool',
    'stream_wrapper_restore': '(string $protocol): bool',
    'stream_wrapper_unregister': '(string $protocol): bool',
    'strftime': '(string $format, ?int $timestamp = null): string|false',
    'strip_tags': '(string $string, $allowed_tags = null): string',
    'stripcslashes': '(string $string): string',
    'stripos': '(string $haystack, string $needle, int $offset = 0): int|false',
    'stripslashes': '(string $string): string',
    'stristr': '(string $haystack, string $needle, bool $before_needle = false): string|false',
    'strlen': '(string $string): int',
    'strnatcasecmp': '(string $string1, string $string2): int',
    'strnatcmp': '(string $string1, string $string2): int',
    'strncasecmp': '(string $string1, string $string2, int $length): int',
    'strncmp': '(string $string1, string $string2, int $length): int',
    'strpbrk': '(string $string, $char_list = \'\', string $characters): string|false',
    'strpos': '(string $haystack, string $needle, int $offset = 0): int|false',
    'strptime': '(string $timestamp, string $format): array|false',
    'strrchr': '(string $haystack, string $needle, bool $before_needle = false): string|false',
    'strrev': '(string $string): string',
    'strripos': '(string $haystack, string $needle, int $offset = 0): int|false',
    'strrpos': '(string $haystack, string $needle, int $offset = 0): int|false',
    'strspn': '(string $string, string $characters, int $offset = 0, ?int $length = null): int',
    'strstr': '(string $haystack, string $needle, bool $before_needle = false): string|false',
    'strtok': '(string $string, $token = null, ?string $token = null): string|false',
    'strtolower': '(string $string): string',
    'strtotime': '(string $datetime, ?int $baseTimestamp = null): int|false',
    'strtoupper': '(string $string): string',
    'strtr': '(string $string, string $from, string $to): string',
    'strval': '(mixed $value): string',
    'substr': '(string $string, int $offset, ?int $length = null)',
    'substr_compare': '(string $haystack, string $needle, int $offset, ?int $length = null, bool $case_insensitive = false): int',
    'substr_count': '(string $haystack, string $needle, int $offset = 0, ?int $length = null): int',
    'substr_replace': '(array|string $string, array|string $replace, array|int $offset, array|int|null $length = null): array|string',
    'symlink': '(string $target, string $link): bool',
    'sys_get_temp_dir': '(): string',
    'sys_getloadavg': '(): array|false',
    'syslog': '(int $priority, string $message)',
    'system': '(string $command, &$result_code = null): string|false',
    'tan': '(float $num): float',
    'tanh': '(float $num): float',
    'tempnam': '(string $directory, string $prefix): string|false',
    'time': '(): int',
    'time_nanosleep': '(int $seconds, int $nanoseconds): array|bool',
    'time_sleep_until': '(float $timestamp): bool',
    'timezone_abbreviations_list': '()',
    'timezone_identifiers_list': '(int $timezoneGroup = DateTimeZone::ALL, ?string $countryCode = null)',
    'timezone_location_get': '(DateTimeZone $object): array|false',
    'timezone_name_from_abbr': '(string $abbr, int $utcOffset = -1, int $isDST = -1): string|false',
    'timezone_name_get': '(DateTimeZone $object): string',
    'timezone_offset_get': '(DateTimeZone $object, DateTimeInterface $datetime)',
    'timezone_open': '(string $timezone): DateTimeZone|false',
    'timezone_transitions_get': '(DateTimeZone $object, int $timestampBegin = PHP_INT_MIN, int $timestampEnd = PHP_INT_MAX): array|false',
    'timezone_version_get': '(): string',
    'tmpfile': '()',
    'touch': '(string $filename, ?int $mtime = null, ?int $atime = null): bool',
    'trait_exists': '(string $trait, bool $autoload = true): bool',
    'trigger_error': '(string $message, int $error_level = E_USER_NOTICE)',
    'trim': '(string $string, string $characters = " \\n\\r\\t\\v\\0"): string',
    'uasort': '(array &$array, callable $callback)',
    'ucfirst': '(string $string): string',
    'ucwords': '(string $string, string $separators = " \\t\\r\\n\\f\\v"): string',
    'uksort': '(array &$array, callable $callback)',
    'umask': '(?int $mask = null): int',
    'uniqid': '(string $prefix = "", bool $more_entropy = false): string',
    'unlink': '(string $filename, $context = null): bool',
    'unpack': '(string $format, string $string, int $offset = 0): array|false',
    'unregister_tick_function': '(callable $callback): void',
    'unserialize': '(string $data, array $options = []): mixed',
    'urldecode': '(string $string): string',
    'urlencode': '(string $string): string',
    'user_error': '(string $message, int $error_level = E_USER_NOTICE)',
    'usleep': '(int $microseconds): void',
    'usort': '(array &$array, callable $callback)',
    'utf8_decode': '(string $string): string',
    'utf8_encode': '(string $string): string',
    'var_dump': '(mixed $value, mixed ...$values): void',
    'var_export': '(mixed $value, bool $return = false): ?string',
    'version_compare': '(string $version1, string $version2, ?string $operator = null): int|bool',
    'vfprintf': '($stream, string $format, array $values): int',
    'vprintf': '(string $format, array $values): int',
    'vsprintf': '(string $format, array $values): string',
    'wordwrap': '(string $string, int $width = 75, string $break = "\\n", bool $cut_long_words = false): string',
    'zend_logo_guid': '(): string',
    'zend_version': '(): string',
}
